apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-send-to-microsoft-teams
spec:
  params:
  - name: webhook-url-secret
    value: microsoft-teams-webhook-url-secret
  - name: webhook-url-secret-key
    value: url
  - name: message
    value: "Hello from Tekton!"
  taskRef:
    name: send-to-microsoft-teams
